# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vjm < Formula
  desc "Vegeta-JMeter Engine - High performance load testing tool compatible with JMeter"
  homepage "https://github.com/xvlet/vjm"
  version "0.1.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xvlet/vjm/releases/download/v0.1.10/vjm_darwin_amd64.tar.gz"
      sha256 "ecf416c1d4afdfa9320a469f32885478ef8bc2f962febb5108f383e3ab7d7828"

      define_method(:install) do
        bin.install "vjm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xvlet/vjm/releases/download/v0.1.10/vjm_darwin_arm64.tar.gz"
      sha256 "530ba147c90d9b78710037d6dba87bee77e7a63c96340db52c5d450c9b2f410b"

      define_method(:install) do
        bin.install "vjm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xvlet/vjm/releases/download/v0.1.10/vjm_linux_amd64.tar.gz"
      sha256 "50012b8c8a8fac11b4ab99a6a96af9b4537414ffcc28473bc053fb862a0510e7"
      define_method(:install) do
        bin.install "vjm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xvlet/vjm/releases/download/v0.1.10/vjm_linux_arm64.tar.gz"
      sha256 "fda4429714b6ce0b711e7dcd5ac856d582033173d47a312edb33e2523e9d3e6d"
      define_method(:install) do
        bin.install "vjm"
      end
    end
  end

  test do
    system "#{bin}/vjm", "--version"
  end
end
