# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vjm < Formula
  desc "Vegeta-JMeter Engine - High performance load testing tool compatible with JMeter"
  homepage "https://github.com/xvlet/vjm"
  version "0.1.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xvlet/vjm/releases/download/v0.1.8/vjm_darwin_amd64.tar.gz"
      sha256 "432204eb4e89dedaa8a112f6e2e50b2a2dec715214ec261a94168db39f532edf"

      define_method(:install) do
        bin.install "vjm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xvlet/vjm/releases/download/v0.1.8/vjm_darwin_arm64.tar.gz"
      sha256 "31a87f0938a26809713ee79746677cf8312bf1df377c843c44a903fe05381214"

      define_method(:install) do
        bin.install "vjm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xvlet/vjm/releases/download/v0.1.8/vjm_linux_amd64.tar.gz"
      sha256 "2b97ee0b5acc46ff65831950ec57decd1f8c5121c9d555a6dd8e9ab557ab7a2a"
      define_method(:install) do
        bin.install "vjm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xvlet/vjm/releases/download/v0.1.8/vjm_linux_arm64.tar.gz"
      sha256 "eef46350d37963bc90ef0383761d2f43376c401f501aa3d63207b6677e77ee37"
      define_method(:install) do
        bin.install "vjm"
      end
    end
  end

  test do
    system "#{bin}/vjm", "--version"
  end
end
